# Generated by Django 5.1 on 2024-08-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='donorprofile',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipientprofile',
            old_name='user_profile',
            new_name='user',
        ),
    ]
