# Generated by Django 5.0.7 on 2024-08-21 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
