# Generated by Django 5.0.7 on 2024-08-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donorprofile_blood_group_donorprofile_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='donation_date',
        ),
    ]
