# Generated by Django 5.0.7 on 2024-08-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_donorprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.userprofile'),
        ),
    ]
