# Generated by Django 5.1 on 2024-08-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_rename_user_profile_bloodrequest_user_and_more'),
        ('donor', '0004_alter_donorregistration_user'),
    ]

    operations = [
    ]
