# Generated by Django 5.1 on 2024-08-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_merge_20240822_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorregistration',
            old_name='registered_at',
            new_name='registration_date',
        ),
    ]
