# Generated by Django 5.1 on 2024-08-22 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_remove_blooddonation_status_alter_blooddonation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
