# Generated by Django 5.1 on 2024-08-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_blooddonation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donorprofile'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.recipientprofile'),
        ),
        migrations.AlterField(
            model_name='donorregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donorprofile'),
        ),
    ]
