# Generated by Django 5.1 on 2024-08-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_alter_blooddonation_user_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donorprofile'),
        ),
    ]
