# Generated by Django 5.1 on 2024-08-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0013_alter_blooddonation_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='camp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donationcamp'),
        ),
    ]
