# Generated by Django 5.1 on 2024-08-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_blooddonation_camp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='donationcamp',
            name='details',
        ),
        migrations.RemoveField(
            model_name='donationcamp',
            name='organizer_contact',
        ),
        migrations.RemoveField(
            model_name='donationcamp',
            name='time',
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
