# Generated by Django 5.1 on 2024-08-23 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0015_remove_blooddonation_camp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='available_blood_types',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
