# Generated by Django 5.1 on 2024-08-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0017_alter_blooddonation_status_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.blooddonation')),
            ],
        ),
    ]
