# Generated by Django 5.1 on 2024-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0018_alter_bloodrequest_status_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
